#!/bin/bash

# This script sets a pomodoro timer

usage () {
  cat <<END
pomidor [-c]

Sets a pomodoro timer, work - 25 min, rest - 5 min
      -c: show countdown (in seconds)
      -h: show this message
END
}

# function to handle errors.
# First argument: error message to print
# Second argument: exit code to exit script with
error () {
  echo "Error: $1"
  usage
  exit $2
} >&2

declare countdown=

while getopts ":hc" opt; do
  case $opt in
    c)
      countdown="yes"
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      error "Unknown option: -${OPTARG}" 3
      ;;
  esac
done

echo "WORK!"

for sec in $(seq 1500 -1 0); do
  if [[ $countdown = "yes" ]]; then
    echo -ne " $sec seconds of work remaining \r"
  fi
  sleep 1
done

echo ""
echo "Rest!"

for sec in $(seq 300 -1 0); do
  if [[ $countdown = "yes" ]]; then
    echo -ne " $sec seconds of rest remaining \r"
  fi
  sleep 1
done

echo ""
echo "End of pomidor session"

exit 0
